# Generated by Django 3.1.4 on 2021-03-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_user_id', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100, null=True)),
                ('nickname', models.CharField(max_length=20)),
                ('describe', models.TextField(default='작성한 소개글이 없습니다.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('author_email', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=False)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('is_fail', models.BooleanField(default=False)),
                ('diff_date', models.PositiveIntegerField()),
                ('claps', models.ManyToManyField(blank=True, related_name='like_posts', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('author_email', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=200)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
