# Generated by Django 3.1.4 on 2020-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HopeCard',
            fields=[
                ('card_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('private_option', models.BooleanField()),
                ('hopes', models.ManyToManyField(to='main.Hope')),
            ],
        ),
    ]
