# Generated by Django 3.1.4 on 2021-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='goal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
